@host = http://localhost:5001

@file_to_process = "/Users/nicksng/Desktop/school/aupp/code/google-drive-html-downloader/all_chats.zip"

@me_list = ["Me","Neron","Neternal Soeung","Ni","konkhmerlaorlek1","neron - ណឺរ៉ូន","neron - ូន","xeno.bozo"]
@remove_list = ["Jockie Music (1)"]
@other_label = SMT

@modules_to_run = dataset_overview, conversation_patterns, relationship_metrics

@session_id =
@task_id =
### Upload one or more chat files (smart processing - sync for small files, async for large)
POST {{host}}/process
Content-Type: multipart/form-data; boundary=----WebAppBoundary

----WebAppBoundary
Content-Disposition: form-data; name="file"; filename="chat1.html"
Content-Type: text/html

< /Users/nicksng/Desktop/school/aupp/code/google-drive-html-downloader/flat_chats/messages2_e6ec677f.html
----WebAppBoundary
###
POST {{host}}/process
Content-Type: multipart/form-data; boundary=----WebAppBoundary

------WebAppBoundary
Content-Disposition: form-data; name="file"; filename="data.html"

< /Users/nicksng/Desktop/school/aupp/code/google-drive-html-downloader/flat_chats/messages2_e6ec677f.html
------WebAppBoundary--

### STEP 2: Check Task Status
GET {{host}}/tasks/status/91679c99-ca1e-4c62-bc8d-5c5e7d9503d2

### STEP 1: Process File
POST {{host}}/process
Content-Type: multipart/form-data; boundary=----WebAppBoundary

------WebAppBoundary
Content-Disposition: form-data; name="file"; filename="data.zip"

< /Users/nicksng/Desktop/school/aupp/code/google-drive-html-downloader/all_chats.zip
------WebAppBoundary--

### STEP 2: Check Task Status
GET {{host}}/tasks/status/b882f602-8aed-4165-ab80-f3b0a513fc3d


### STEP 3: Filter Data
POST {{host}}/filter
Content-Type: application/json

{
  "me": {{me_list}},
  "remove": {{remove_list}},
  "other_label": "{{other_label}}"
}

### STEP 4: Analyze Data
POST {{host}}/analyze
Content-Type: application/json


###
GET {{host}}/tasks/session


### Clear Session
POST {{host}}/session/clear


### Download PROCESSED messages
GET {{host}}/data/processed

### Download FILTERED messages
GET {{host}}/data/filtered

### Download the ANALYSIS report
GET {{host}}/data/report

###
POST {{host}}/search/fuzzy
Content-Type: application/json

{
  "query": "sl o kapin",
  "cutoff": 70
}
