
@host = http://localhost:5001

#@file_to_process = "/Users/nicksng/Desktop/school/aupp/code/google-drive-html-downloader/all_chats.zip"
#
#@me_list = ["Me","Neron","Neternal Soeung","Ni","konkhmerlaorlek1","neron - ណឺរ៉ូន","neron - ូន","xeno.bozo"]
#@remove_list = ["Jockie Music (1)"]
#@other_label = SMT
#
#@modules_to_run = dataset_overview, conversation_patterns, relationship_metrics

#@session_id =
#@task_id =
### Upload one or more chat files (smart processing - sync for small files, async for large)
POST {{host}}/process
Content-Type: multipart/form-data; boundary=----WebAppBoundary

----WebAppBoundary
Content-Disposition: form-data; name="file"; filename="chat1.html"
Content-Type: text/html

< /Users/nicksng/Desktop/school/aupp/code/google-drive-html-downloader/flat_chats/messages2_e6ec677f.html
----WebAppBoundary
###

POST {{host}}/process
Content-Type: multipart/form-data; boundary=----WebAppBoundary

------WebAppBoundary
Content-Disposition: form-data; name="file"; filename="data.html"

< /Users/nicksng/Desktop/school/aupp/code/google-drive-html-downloader/flat_chats/messages2_e6ec677f.html
------WebAppBoundary--


### STEP 1: Process File
POST {{host}}/process
Content-Type: multipart/form-data; boundary=----WebAppBoundary

------WebAppBoundary
Content-Disposition: form-data; name="file"; filename="data.zip"

< C:\Users\phear\Downloads\Telegram Desktop\all_chats.zip
------WebAppBoundary--

### STEP 3: Filter Data
POST {{host}}/filter
Content-Type: application/json

{
  "me": ["Me","Neron","Neternal Soeung","Ni","konkhmerlaorlek1","neron - ណឺរ៉ូន","neron - ូន","xeno.bozo"],
  "remove": ["Jockie Music (1)"],
  "other_label": "other"
}

### STEP 4: Analyze Data
POST {{host}}/analyze
Content-Type: application/json

### STEP 4: Analyze Data
POST {{host}}/analyze
Content-Type: application/json

{
  "modules_to_run": [
    "dataset_overview"
  ]
}

###
POST {{host}}/search/fuzzy
Content-Type: application/json

{
  "query": "sl o kapin",
  "cutoff": 70
}
