@host = http://localhost:5001

### STEP 2: Check Task Status
GET {{host}}/tasks/status/4fdfa789-c33a-454c-abd4-45f82c0ff591

###
GET {{host}}/tasks/session

### Clear Session
POST {{host}}/session/clear