@host = http://localhost:5001

### STEP 2: Check Task Status
GET {{host}}/tasks/status/981f7ed8-61da-4b82-bfe1-2e1efd67dd5a

###
GET {{host}}/tasks/session

### Clear Session
POST {{host}}/session/clear