@host = http://localhost:5001

### STEP 2: Check Task Status
GET {{host}}/tasks/status/17a8a03a-db3d-4b64-95e4-75c01f55d71c

###
GET {{host}}/tasks/session

### Clear Session
POST {{host}}/session/clear